/**
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * Dustpan
 * A tool to uncover WikiProjects that can be improved on Wikidata
 * @see https://github.com/wikicollabs/dustpan
 *
 * Scope options lookup.
 *
 * Reads a scope's selectable values from catalog/scopeOptions.json,
 * generated by scripts/updateScopes.ts, and returns them labeled and
 * sorted for the requested display language. Async by contract, so
 * callers don't depend on where the options come from.
 */

import scopeOptionsJson from '../catalog/scopeOptions.json';
import type { ScopeOption } from '../types/types';

type ValueLabels = Record<string, string>; // lang code -> label
type ScopeOptionsCache = Record<string, Record<string, ValueLabels>>; // scopeId -> QID -> labels

const scopeOptions = scopeOptionsJson as ScopeOptionsCache;

// Returns [{ value: qid, label: string }] sorted by label, [] for an unknown
// scopeId (logged, not thrown, so callers can render an empty dropdown).
export async function fetchScopeOptions(scopeId: string, lang = 'en'): Promise<ScopeOption[]> {
  const values = scopeOptions[scopeId];
  if (!values) {
    console.error(`[Dustpan] unknown scopeId: ${scopeId}`);
    return [];
  }

  // Falls back to en when the cache predates a newly added display language.
  const options: ScopeOption[] = Object.entries(values).map(([qid, labels]) => ({
    value: qid,
    label: labels[lang] ?? labels.en ?? qid,
  }));
  options.sort((a, b) => a.label.localeCompare(b.label, lang));
  return options;
}